### ISSUE TITLE
Modifications des ses données perso + ajout avatar

### ISSUE THREAD

**Issue by adrien-glanum** [LeoVincentGlanum/AJEG#27]
featlot2/edit-user-info

**Comment by florian-glanum** [comment]
après pull et storage:link les image sont bien transmise dans public mais pas chargé dans la vue html

**Comment by florian-glanum** [comment]
ajout de la fonctionnalité modifier son mots de passe en renseignent le mots de passe courant pour la verification

**Comment by LeoVincentGlanum** [comment]
CC ok mis sur lot2
